### PR TITLE
Upgrade Tooltipster to newest version

### PR DESCRIPTION
**Pull request by meowsus**
Here's the newest version.

### CODE REVIEW

**Comment by meowsus** [comment]
Hey @Amunds 

It would be really helpful for my team if you could take the time to merge this work and cut a new gem to rubygems.org.

Alternatively, I wouldn't mind taking over this repository and push access to the rubygems project if you don't feel like maintaining this any longer.

Thanks in advance for your help!

**Comment by Amunds** [comment]
I do apologize for not getting back to you. I've sent you a collaborator request and if you could please provide me with the email you use on Rubygems I'll add you as an owner. The one listed on Github is not registered on Rubygems. You can send the email address to my email if you don't want it listed here.

**Comment by Amunds** [comment]
@meowsus, 
I see you haven't merged or pushed to Rubygems yet, just wanted to make sure everything is set up correctly.

**Comment by meowsus** [comment]
@Amunds sorry for the delay. What a wild week. I merged the work, added a new tag to git, and pushed to rubygems.org just fine. Thanks for your help and for adding me as a contributor.

**Pull request merged**
